"""Generate the exact used SVG path catalog from the pinned, attributed source snapshot.

Snapshot extracted from MudBlazor 9.0.0 public Material icon constants (MIT);
the original Google Material Icons artwork is Apache-2.0. See THIRD-PARTY-NOTICES.md.
The snapshot makes regeneration independent of the removed runtime package.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

def generate():
    paths = json.loads((Path(__file__).parent / "material-icon-paths.json").read_text(encoding="utf-8"))
    lines = ["// Generated by scripts/icons/generate-material-icons.py. See THIRD-PARTY-NOTICES.md.",
             "namespace MediaEngine.Web.Components.Shared;", "", "public static class AppMaterialIcons", "{"]
    for family in ("Filled", "Outlined", "Uncategorized"):
        lines += [f"    public static class {family}", "    {"]
        for key, value in sorted(paths.items()):
            if key.startswith(family + "."):
                escaped = value.replace('"', '""')
                lines.append(f'        public const string {key.split(".")[1]} = @"{escaped}";')
        lines.append("    }")
    lines += ["}", ""]
    return "\n".join(lines)

if __name__ == "__main__":
    destination = ROOT / "src/MediaEngine.Web/Components/Shared/AppMaterialIconPaths.cs"
    destination.write_text(generate(), encoding="utf-8", newline="\n")
    print(f"Generated {destination.relative_to(ROOT)}")
